version: '3.5'

networks:
  kolibri-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/16

services:
  kolibri1:
    image: kolibri-base:0.1.0-alpha2
    ports:
      - "8000:8000"
    environment:
      PROFILE: prod
      ROLES: compute,httpserver
      CLUSTER_NODE_HOST: 172.33.1.1
      CLUSTER_NODE_PORT: 8001
      HTTP_SERVER_INTERFACE: 172.33.1.1
      HTTP_SERVER_PORT: 8000
      MANAGEMENT_HOST: 172.33.1.1
      MANAGEMENT_PORT: 8558
      MANAGEMENT_BIND_HOSTNAME: '0.0.0.0'
      MANAGEMENT_BIND_PORT: 8558
      CLUSTER_NODE_BIND_HOST: '0.0.0.0'
      CLUSTER_NODE_BIND_PORT: 8001
      DISCOVERY_SERVICE_NAME: kolibri-service
      KOLIBRI_ACTOR_SYSTEM_NAME: KolibriAppSystem
      DISCOVERY_METHOD: config
    volumes:
      - ./kolibri-test:/app/data
    networks:
      kolibri-net:
        ipv4_address: 172.33.1.1

  kolibri2:
    image: kolibri-base:0.1.0-alpha2
    environment:
      PROFILE: prod
      ROLES: compute
      CLUSTER_NODE_HOST: 172.33.1.2
      CLUSTER_NODE_PORT: 8001
      MANAGEMENT_HOST: 172.33.1.2
      MANAGEMENT_PORT: 8559
      MANAGEMENT_BIND_HOSTNAME: '0.0.0.0'
      MANAGEMENT_BIND_PORT: 8559
      CLUSTER_NODE_BIND_HOST: '0.0.0.0'
      CLUSTER_NODE_BIND_PORT: 8001
      DISCOVERY_SERVICE_NAME: kolibri-service
      KOLIBRI_ACTOR_SYSTEM_NAME: KolibriAppSystem
      DISCOVERY_METHOD: config
    volumes:
      - ./kolibri-test:/app/data
    networks:
      kolibri-net:
        ipv4_address: 172.33.1.2


  kolibri3:
    image: kolibri-base:0.1.0-alpha2
    environment:
      PROFILE: prod
      ROLES: compute
      CLUSTER_NODE_HOST: 172.33.1.3
      CLUSTER_NODE_PORT: 8001
      MANAGEMENT_HOST: 172.33.1.3
      MANAGEMENT_PORT: 8560
      MANAGEMENT_BIND_HOSTNAME: '0.0.0.0'
      MANAGEMENT_BIND_PORT: 8560
      CLUSTER_NODE_BIND_HOST: '0.0.0.0'
      CLUSTER_NODE_BIND_PORT: 8001
      DISCOVERY_SERVICE_NAME: kolibri-service
      KOLIBRI_ACTOR_SYSTEM_NAME: KolibriAppSystem
      DISCOVERY_METHOD: config
    volumes:
      - ./kolibri-test:/app/data
    networks:
      kolibri-net:
        ipv4_address: 172.33.1.3

