version: '3.5'

services:

  prometheus:
    image: prom/prometheus:v2.28.1
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      # /prometheus is the default data dir
      - ./prometheus/data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:8.0.5
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    # user setting needed to be set to owner/group of the volume (above grafana folder on host machine)
    user: "1000:1000"

  kolibri1:
    image: kolibri-base:0.1.0-alpha3
    ports:
      - "8000:8000"
      - "5266:5266"
      - "9095:9095"
    environment:
      JVM_OPTS: >
        -XX:+PrintFlagsFinal
        -XX:+UseG1GC
        -Xms1024m
        -Xmx4096m
      PROFILE: prod
      ROLES: httpserver
      CLUSTER_NODE_HOST: kolibri1
      CLUSTER_NODE_PORT: 8001
      HTTP_SERVER_INTERFACE: kolibri1
      HTTP_SERVER_PORT: 8000
      MANAGEMENT_HOST: kolibri1
      MANAGEMENT_PORT: 8558
      MANAGEMENT_BIND_HOSTNAME: '0.0.0.0'
      MANAGEMENT_BIND_PORT: 8558
      CLUSTER_NODE_BIND_HOST: '0.0.0.0'
      CLUSTER_NODE_BIND_PORT: 8001
      DISCOVERY_SERVICE_NAME: kolibri-service
      KOLIBRI_ACTOR_SYSTEM_NAME: KolibriAppSystem
      DISCOVERY_METHOD: config
    volumes:
      - ./kolibri-test:/app/data
    mem_limit: 4200m

  kolibri2:
    image: kolibri-base:0.1.0-alpha3
    environment:
      JVM_OPTS: >
        -XX:+PrintFlagsFinal
        -XX:+UseG1GC
        -Xms1024m
        -Xmx4096m
      PROFILE: prod
      ROLES: compute
      CLUSTER_NODE_HOST: kolibri2
      CLUSTER_NODE_PORT: 8001
      MANAGEMENT_HOST: kolibri2
      MANAGEMENT_PORT: 8559
      MANAGEMENT_BIND_HOSTNAME: '0.0.0.0'
      MANAGEMENT_BIND_PORT: 8559
      CLUSTER_NODE_BIND_HOST: '0.0.0.0'
      CLUSTER_NODE_BIND_PORT: 8001
      DISCOVERY_SERVICE_NAME: kolibri-service
      KOLIBRI_ACTOR_SYSTEM_NAME: KolibriAppSystem
      DISCOVERY_METHOD: config
    volumes:
      - ./kolibri-test:/app/data
    mem_limit: 4200m


  kolibri3:
    image: kolibri-base:0.1.0-alpha3
    environment:
      JVM_OPTS: >
        -XX:+PrintFlagsFinal
        -XX:+UseG1GC
        -Xms1024m
        -Xmx4069m
      PROFILE: prod
      ROLES: compute
      CLUSTER_NODE_HOST: kolibri3
      CLUSTER_NODE_PORT: 8001
      MANAGEMENT_HOST: kolibri3
      MANAGEMENT_PORT: 8560
      MANAGEMENT_BIND_HOSTNAME: '0.0.0.0'
      MANAGEMENT_BIND_PORT: 8560
      CLUSTER_NODE_BIND_HOST: '0.0.0.0'
      CLUSTER_NODE_BIND_PORT: 8001
      DISCOVERY_SERVICE_NAME: kolibri-service
      KOLIBRI_ACTOR_SYSTEM_NAME: KolibriAppSystem
      DISCOVERY_METHOD: config
    volumes:
      - ./kolibri-test:/app/data
    mem_limit: 4200m
