{{- if .Values.localVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kolibri-local-volume-readwrite
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  # for kind setup set path to containerPath the local
  # node's storage (your local machine's) volume is mounted to
  # see kind cluster config in start-kind-with-registry.sh script
  hostPath:
    path: {{ .Values.localVolume.hostPathReadWrite }}
{{- end }}