{{- if .Values.localVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kolibri-pv-claim
spec:
  volumeName: kolibri-local-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  {{- end }}