apiVersion: v1
kind: Service
metadata:
  name: {{ include "kolibri-service.fullname" . }}
  labels:
    {{- include "kolibri-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: app-http
      protocol: TCP
      name: service-http
  selector:
    # limit this to the http node, we dont want to expose the compute pods
    # as service
    {{- include "kolibri-service.selectorLabels" . | nindent 4 }}
    {{- include "kolibri-service.selectorLabelsHttp" . | nindent 4 }}
