{
 "title": "Kamon 2.x - API dashboard",
 "description": "API dashboard for apps instrumented with Kamon 2.x",
 "tags": [
  "kamon",
  "prometheus",
  "web-server"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "app_filter", "label": "App filter", "query": "my-app.*|another-app.*" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(up{job=~\"$app_filter\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "client_operation",
    "query": {
     "query": "label_values(span_processing_time_seconds_count{job=~\"$job\", span_kind=\"client\"},operation)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput (avg. $interval)",
   "type": "graph",
   "description": "The average requests rate in the last $interval across all selected instances stacked by status",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (increase(http_server_requests_total{http_status_code=\"2xx\"}[$interval]))",
     "legendFormat": "2xx rpm - {{instance}}"
    },
    {
     "expr": "sum by (instance)(increase(http_server_requests_total{http_status_code=\"3xx\"}[$interval]))",
     "legendFormat": "3xx rpm"
    },
    {
     "expr": "sum by (instance)(increase(http_server_requests_total{http_status_code=\"4xx\"}[$interval]))",
     "legendFormat": "4xx rpm"
    },
    {
     "expr": "sum by (instance)(increase(http_server_requests_total{http_status_code=\"5xx\"}[$interval]))",
     "legendFormat": "5xx rpm"
    }
   ]
  },
  {
   "title": "Latency: only 2xx status response",
   "type": "graph",
   "description": "Latency of requests with 2xx status response over $interval",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(span_processing_time_seconds_bucket{span_kind=\"server\", http_status_code=~\"2.*\"}[$interval])) by (le))",
     "legendFormat": "p99.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(span_processing_time_seconds_bucket{span_kind=\"server\", http_status_code=~\"2.*\"}[$interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(span_processing_time_seconds_bucket{span_kind=\"server\", http_status_code=~\"2.*\"}[$interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(span_processing_time_seconds_bucket{span_kind=\"server\", http_status_code=~\"2.*\"}[$interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Approximated Uptime: 'requests with 2xx status response' / 'requests with 2xx or 5xx status response'",
   "type": "graph",
   "description": "Given:\n  * Success requests: status 2xx\n  * Valid requests: status 2xx or status 5xx\n\nThe uptime could be estimated by 'success requests' / 'valid requests'.\n\nThis is just an approximation because it doesn't take in account a lot of corner cases. For a more accurate metric it should be measured from outside the app.\n",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total{http_status_code=\"2xx\"}[$interval]))\n /\n sum(rate(http_server_requests_total{http_status_code=~\"2xx|5xx\"}[$interval]))",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "2xx | 4xx | 3xx | 5xx % (avg. $interval)",
   "type": "graph",
   "description": "Relative frequency distribution of response 2xx, 3xx, 4xx and 5xx over $interval",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total{http_status_code=\"5xx\"}[$interval]))\n/\nsum(rate(http_server_requests_total[$interval]))",
     "legendFormat": "Failures (5xx)"
    },
    {
     "expr": "sum(rate(http_server_requests_total{http_status_code=\"4xx\"}[$interval]))\n/\nsum(rate(http_server_requests_total[$interval]))",
     "legendFormat": "Client errors (4xx)"
    },
    {
     "expr": "sum(rate(http_server_requests_total{http_status_code=\"3xx\"}[$interval]))\n/\nsum(rate(http_server_requests_total[$interval]))",
     "legendFormat": "Redirects (3xx)"
    },
    {
     "expr": "sum(rate(http_server_requests_total{http_status_code=\"2xx\"}[$interval]))\n/\nsum(rate(http_server_requests_total[$interval]))",
     "legendFormat": "Success (2xx)"
    }
   ]
  },
  {
   "title": "Latency: only 3xx status response",
   "type": "graph",
   "description": "Latency of requests with 3xx status response over $interval",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(span_processing_time_seconds_bucket{span_kind=\"server\", http_status_code=~\"3.*\"}[$interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(span_processing_time_seconds_bucket{span_kind=\"server\", http_status_code=~\"3.*\"}[$interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(span_processing_time_seconds_bucket{span_kind=\"server\", http_status_code=~\"3.*\"}[$interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Latency: only 4xx status response",
   "type": "graph",
   "description": "Latency of requests with 4xx status response over $interval",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(span_processing_time_seconds_bucket{span_kind=\"server\", http_status_code=~\"4.*\"}[$interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(span_processing_time_seconds_bucket{span_kind=\"server\", http_status_code=~\"4.*\"}[$interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(span_processing_time_seconds_bucket{span_kind=\"server\", http_status_code=~\"4.*\"}[$interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Latency: only 5xx status response",
   "type": "graph",
   "description": "Latency of requests with 5xx status response over $interval",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(span_processing_time_seconds_bucket{span_kind=\"server\", http_status_code=~\"5.*\"}[$interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(span_processing_time_seconds_bucket{span_kind=\"server\", http_status_code=~\"5.*\"}[$interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(span_processing_time_seconds_bucket{span_kind=\"server\", http_status_code=~\"5.*\"}[$interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Clients metrics | $client_operation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "repeat": "client_operation"
  },
  {
   "title": "Throughput of outgoing requests over $interval",
   "type": "graph",
   "description": "The average outgoing requests rate in the last $interval across all selected instances",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum by (operation)(increase(span_processing_time_seconds_count{error=\"false\", span_kind=\"client\"}[$interval]))",
     "legendFormat": "{{operation}} with no error"
    },
    {
     "expr": "sum by (operation)(increase(span_processing_time_seconds_count{error=\"true\", span_kind=\"client\"}[$interval]))",
     "legendFormat": "{{operation}} with error"
    }
   ]
  },
  {
   "title": "Latency of outgoing requests over $interval",
   "type": "graph",
   "description": "Latency of outgoing requests in the last $interval across all selected instances",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(span_processing_time_seconds_bucket{span_kind=\"client\", error=\"false\"}[$interval])) by (le))",
     "legendFormat": "p99 {{operation}} with no error"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(span_processing_time_seconds_bucket{span_kind=\"client\", error=\"true\"}[$interval])) by (le, instance))",
     "legendFormat": "p99 {{operation}} with error"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(span_processing_time_seconds_bucket{span_kind=\"client\", error=\"false\"}[$interval])) by (le, instance, operation))",
     "legendFormat": "p90 {{operation}} with no error"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(span_processing_time_seconds_bucket{span_kind=\"client\", error=\"true\"}[$interval])) by (le, instance, operation))",
     "legendFormat": "p90 {{operation}} with error"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(span_processing_time_seconds_bucket{span_kind=\"client\", error=\"false\"}[$interval])) by (le, instance, operation))",
     "legendFormat": "p50 {{operation}} with no error"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(span_processing_time_seconds_bucket{span_kind=\"client\", error=\"true\"}[$interval])) by (le, instance, operation))",
     "legendFormat": "p50 {{operation}} with error"
    }
   ]
  }
 ]
}