{
 "title": "Kolibri Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DATASOURCE", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Actors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unprocessed Messages",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(akka_system_dead_letters_total{system=\"KolibriAppSystem\"}[$__range]))",
     "legendFormat": "Dead Letters"
    },
    {
     "expr": "sum(increase(akka_system_unhandled_messages_total{system=\"KolibriAppSystem\"}[$__range]))",
     "legendFormat": "Unhandled"
    }
   ]
  },
  {
   "title": "Processed Messages",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(akka_system_processed_messages_total{system=\"KolibriAppSystem\", tracked=\"true\"}[$__range]))",
     "legendFormat": "tracked"
    },
    {
     "expr": "sum(increase(akka_system_processed_messages_total{system=\"KolibriAppSystem\", tracked=\"false\"}[$__range]))",
     "legendFormat": "untracked"
    }
   ]
  },
  {
   "title": "Active Actors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(akka_system_active_actors_sum[120s]) / rate(akka_system_active_actors_count[120s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Actor Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (class) (increase(akka_actor_errors_total[5m]))",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Mailbox Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (class) (increase(akka_actor_mailbox_size_sum[120s]) / increase(akka_actor_mailbox_size_count[120s]))",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Time in Mailbox (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(akka_actor_time_in_mailbox_seconds_bucket[2m])) by (le, class)) * 1000",
     "legendFormat": "p99 - {{class}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(akka_actor_time_in_mailbox_seconds_bucket[2m])) by (le, class)) * 1000",
     "legendFormat": "p95 - {{class}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(akka_actor_time_in_mailbox_seconds_bucket[2m])) by (le, class)) * 1000",
     "legendFormat": "p90 - {{class}}"
    }
   ]
  },
  {
   "title": "Actor Processing Times (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(akka_actor_processing_time_seconds_bucket[2m])) by (le, class)) * 1000",
     "legendFormat": "p99 - {{class}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(akka_actor_processing_time_seconds_bucket[2m])) by (le, class)) * 1000",
     "legendFormat": "p95 - {{class}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(akka_actor_processing_time_seconds_bucket[2m])) by (le, class)) * 1000",
     "legendFormat": "p90 - {{class}}"
    }
   ]
  },
  {
   "title": "Job Manager Actor Processing Times (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(akka_actor_processing_time_seconds_bucket{class=\"de.awagen.kolibri.fleet.akka.actors.work.manager.JobManagerActor\"}[2m])) by (le, class)) * 1000",
     "legendFormat": "p99 - {{class}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(akka_actor_processing_time_seconds_bucket{class=\"de.awagen.kolibri.fleet.akka.actors.work.manager.JobManagerActor\"}[2m])) by (le, class)) * 1000",
     "legendFormat": "p95 - {{class}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(akka_actor_processing_time_seconds_bucket{class=\"de.awagen.kolibri.fleet.akka.actors.work.manager.JobManagerActor\"}[2m])) by (le, class)) * 1000",
     "legendFormat": "p90 - {{class}}"
    }
   ]
  },
  {
   "title": "Runnable Execution Actor Processing Times (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(akka_actor_processing_time_seconds_bucket{class=\"de.awagen.kolibri.fleet.akka.actors.work.worker.RunnableExecutionActor\"}[2m])) by (le, class)) * 1000",
     "legendFormat": "p99 - {{class}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(akka_actor_processing_time_seconds_bucket{class=\"de.awagen.kolibri.fleet.akka.actors.work.worker.RunnableExecutionActor\"}[2m])) by (le, class)) * 1000",
     "legendFormat": "p95 - {{class}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(akka_actor_processing_time_seconds_bucket{class=\"de.awagen.kolibri.fleet.akka.actors.work.worker.RunnableExecutionActor\"}[2m])) by (le, class)) * 1000",
     "legendFormat": "p90 - {{class}}"
    }
   ]
  },
  {
   "title": "Aggregating Actor Processing Times (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(akka_actor_processing_time_seconds_bucket{class=\"de.awagen.kolibri.fleet.akka.actors.work.worker.AggregatingActor\"}[2m])) by (le, class)) * 1000",
     "legendFormat": "p99 - {{class}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(akka_actor_processing_time_seconds_bucket{class=\"de.awagen.kolibri.fleet.akka.actors.work.worker.AggregatingActor\"}[2m])) by (le, class)) * 1000",
     "legendFormat": "p95 - {{class}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(akka_actor_processing_time_seconds_bucket{class=\"de.awagen.kolibri.fleet.akka.actors.work.worker.AggregatingActor\"}[2m])) by (le, class)) * 1000",
     "legendFormat": "p90 - {{class}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Requests/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "targets": [
    {
     "expr": "sum by (operation, instance)(increase(span_processing_time_seconds_count{error=\"false\", span_kind=\"client\"}[1m]))",
     "legendFormat": "{{operation}} on {{instance}} with no error"
    },
    {
     "expr": "sum by (operation, instance)(increase(span_processing_time_seconds_count{error=\"true\", span_kind=\"client\"}[1m]))",
     "legendFormat": "{operation}} on {{instance}} with error"
    }
   ]
  },
  {
   "title": "Client Request time (in ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by (instance, http_method)(increase(span_processing_time_seconds_sum{span_kind=\"client\"}[2m]) / increase(span_processing_time_seconds_count[2m])) * 1000",
     "legendFormat": "avg - method={{http_method}}, instance={{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(span_processing_time_seconds_bucket{span_kind=\"client\"}[2m])) by (le, instance, http_method)) * 1000",
     "legendFormat": "p99 - method={{http_method}}, instance={{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(span_processing_time_seconds_bucket{span_kind=\"client\"}[2m])) by (le, instance, http_method)) * 1000",
     "legendFormat": "p95 - method={{http_method}}, instance={{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(span_processing_time_seconds_bucket{span_kind=\"client\"}[2m])) by (le, instance, http_method)) * 1000",
     "legendFormat": "p90 - method={{http_method}}, instance={{instance}}"
    }
   ]
  },
  { "title": "System (JVM)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Avg CPU Load (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "avg(rate(host_cpu_usage_sum{mode!~\"idle\"}[5m:1m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "max(rate(host_cpu_usage_sum{mode!~\"idle\"}[5m:1m]))",
     "legendFormat": "max"
    },
    {
     "expr": "min(rate(host_cpu_usage_sum{mode!~\"idle\"}[5m:1m]))",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Nr of GCs (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    { "expr": "rate(jvm_gc_seconds_count[1m])", "legendFormat": "{{generation}}-{{instance}}" }
   ]
  },
  {
   "title": "Avg GC times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "rate(jvm_gc_seconds_sum[1m]) / rate(jvm_gc_seconds_count[1m])",
     "legendFormat": "{{generation}}-{{instance}}"
    }
   ]
  },
  {
   "title": "GC time (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    { "expr": "rate(jvm_gc_seconds_sum[1m])", "legendFormat": "{{generation}}-{{instance}}" }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes * 0.000001",
     "legendFormat": "Total (MB) - {{instance}}"
    },
    {
     "expr": "jvm_memory_committed_bytes * 0.000001",
     "legendFormat": "Commited (MB) - {{instance}}"
    },
    {
     "expr": "avg by (instance)(rate(jvm_memory_pool_used_bytes_sum[5m])) * 0.000001",
     "legendFormat": "Used (MB) - {{instance}}"
    }
   ]
  }
 ]
}