apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: kolibri-config-workernode
data:
  PROFILE: 'prod'
  ROLES: 'compute'
  KAMON_PROMETHEUS_PORT: '9095'
  KAMON_STATUSPAGE_PORT: '5266'
  CLUSTER_NODE_HOST: '<getHostAddress>'
  CLUSTER_NODE_PORT: '8001'
  CLUSTER_NODE_BIND_HOST: '0.0.0.0'
  CLUSTER_NODE_BIND_PORT: '8001'
  MANAGEMENT_HOST: '<getHostAddress>'
  MANAGEMENT_PORT: '8558'
  MANAGEMENT_BIND_HOSTNAME: '0.0.0.0'
  MANAGEMENT_BIND_PORT: '8558'
  DISCOVERY_SERVICE_NAME: 'kolibri-service'
  KOLIBRI_ACTOR_SYSTEM_NAME: 'KolibriAppSystem'
  DISCOVERY_METHOD: 'kubernetes-api'
  REQUEST_PARALLELISM: '16'
  USE_CONNECTION_POOL_FLOW: 'false'
  RUNNING_TASK_PER_JOB_MAX_COUNT: '20'
  RUNNING_TASK_PER_JOB_DEFAULT_COUNT: '2'
  KOLIBRI_DISPATCHER_PARALLELISM_MIN: '8'
  KOLIBRI_DISPATCHER_PARALLELISM_FACTOR: '8.0'
  KOLIBRI_DISPATCHER_PARALLELISM_MAX: '32'
  KOLIBRI_DISPATCHER_THROUGHPUT: '10'
  DEFAULT_DISPATCHER_PARALLELISM_FACTOR: '1.0'
  DEFAULT_DISPATCHER_PARALLELISM_MAX: '2'
  DEFAULT_DISPATCHER_PARALLELISM_MIN: '1'
  HTTP_CLIENT_CONNECTION_TIMEOUT: '5s'
  HTTP_CLIENT_IDLE_TIMEOUT: '10s'
  HTTP_CONNECTION_POOL_MAX_OPEN_REQUESTS: '1024'
  HTTP_CONNECTION_POOL_MAX_RETRIES: '3'
  HTTP_CONNECTION_POOL_MAX_CONNECTIONS: '1024'
  HTTP_CONNECTION_POOL_SUBSCRIPTION_TIMEOUT: '60 seconds'
  USE_RESULT_ELEMENT_GROUPING: 'true'
  RESULT_ELEMENT_GROUPING_COUNT: '2000'
  RESULT_ELEMENT_GROUPING_INTERVAL_IN_MS: '1000'
  RESULT_ELEMENT_GROUPING_PARALLELISM: '1'
  USE_AGGREGATOR_BACKPRESSURE: 'true'
  AGGREGATOR_RECEIVE_PARALLELISM: '32'
  MAX_NR_BATCH_RETRIES: '2'
  PERSISTENCE_MODE: 'GCP'
  # TODO: replace placeholder with used bucket name
  GCP_GS_BUCKET: '##GCP_GS_BUCKET'
  # TODO: replace placeholder with used bucket path (can be empty string if paths shall be starting on root bucket level)
  GCP_GS_PATH: '##GCP_GS_PATH'
  # TODO: replace placeholder with used project id
  GCP_GS_PROJECT_ID: '##GCP_GS_PROJECT_ID'
  JOB_TEMPLATES_PATH: 'templates/jobs'
  JUDGEMENT_FILE_SOURCE_TYPE: 'JSON_LINES'
  JUDGEMENT_FILE_JSON_LINES_JUDGEMENT_VALUE_TYPE_CAST: 'STRING'
  USE_INSECURE_SSL_ENGINE: 'true'
  USE_SHARDING_AND_ENDPOINTS: 'true'
