{{- if .Values.localVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kolibri-pv-readwrite-claim
spec:
  volumeName: kolibri-local-volume-readwrite
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{- end }}