apiVersion: v1
kind: Service
metadata:
  name: {{ include "kolibri-service.fullnameCompute" . }}
  labels:
    {{- include "kolibri-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9095
      targetPort: 9095
      protocol: TCP
      name: service-prometheus
  selector:
    # limit this to the http node, we dont want to expose the compute pods
    # as service
    {{- include "kolibri-service.selectorLabels" . | nindent 4 }}
    {{- include "kolibri-service.selectorLabelsCompute" . | nindent 4 }}
