{
 "title": "Kolibri Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DATASOURCE", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests/min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum by (method, contextPath, responseCode)(increase(countClientRequests[1m]))",
     "legendFormat": "{{method}}|{{contextPath}}|{{responseCode}}"
    }
   ]
  },
  {
   "title": "Client Request time (in ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(externalRequestTimer_bucket[1m])) by (le, contextPath, method, responseCode))",
     "legendFormat": "p99|{{method}}|{{contextPath}}|{{responseCode}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(externalRequestTimer_bucket[1m])) by (le, contextPath, method))",
     "legendFormat": "p50|{{method}}|{{contextPath}}"
    }
   ]
  },
  { "title": "System (JVM)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Load (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg by (instance) (rate(process_cpu_seconds_total[1m]))",
     "legendFormat": "Load-{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (instance)(jvm_memory_bytes_max) * 0.000001",
     "legendFormat": "Max (MB) - {{instance}}"
    },
    {
     "expr": "sum by (instance)(jvm_memory_bytes_committed) * 0.000001",
     "legendFormat": "Committed (MB) - {{instance}}"
    },
    {
     "expr": "sum by (instance)(jvm_memory_bytes_used) * 0.000001",
     "legendFormat": "Used (MB) - {{instance}}"
    }
   ]
  }
 ]
}