apiVersion: apps/v1
kind: Deployment
metadata:
  name: kolibri-service
spec:
  template:
    spec:
#      TODO: if any nodeSelector wanted, fill in here
#      nodeSelector:
#        someTypeKey: [value]
      containers:
        - name: kolibri-service
          image: awagen/kolibri-base:0.1.0-rc1
          imagePullPolicy: Always
